### ISSUE TITLE
React Router4 - Alternative of OnEnter

### ISSUE THREAD

**Issue by dipesh008** [bernabe9/redux-react-session#14]
Hi,
I am unable to figure out how to put restrictions on private routes. In React Router4, onEnter is removed. 

Store listener is not working as the event (@@redux-react-session/GET_SESSION_SUCCESS) is ASYNC. 

How to check if the user is authenticated. 

@bernabe9  Any help on this is appreciated. 

Thank you in Advance.

**Comment by bernabe9** [comment]
Hi @dipesh008,
Here is a simple example using an alternative of OnEnter with async authorization and `redux-react-session`: https://github.com/bernabe9/react-router-v4-auth-example

Check out this component `PrivateRoute`: https://github.com/bernabe9/redux-react-session/blob/master/examples/react-router-v4-example/src/components/PrivateRoute.js

The `PrivateRoute` component receive a prop `authenticated`, and then in the render prop of the `Route` component you can choose what to do depending on the the `authenticated` prop value.

```javascript
const PrivateRoute = ({ component, exact = false, path, authenticated }) => (
  <Route
    exact={exact}
    path={path}
    render={props => (
      authenticated ? (
        React.createElement(component, props)
      ) : (
        <Redirect to={{
          pathname: '/login',
          state: { from: props.location }
        }}/>
      )
    )}
  />
);
``` 

Hope this helps!

**Comment by bernabe9** [comment]
I know that `react-redux-session` fetches the session in an async way, for that it provides the flag `checked` to check if the session was already fetched.

Here is how it is used in the App component:
```javascript
const App = ({ authenticated, checked }) => (
  <Router>
    { checked &&
      <div>
        <PrivateRoute exact path="/" component={Home} authenticated={authenticated}/>
        <Route path="/login" component={Login}/>
      </div>
    }
  </Router>
);
```

So, the first time that `PrivateRoute` is rendered the session was already fetched and you are sure that the value of `authenticated` is the real value.

**Comment by dipesh008** [comment]
Thank you @bernabe9  

Now it is clear why `checked ` is added.  If we can add this to the document, it will help others too.
