### ISSUE TITLE
able to login and redirecting to home page but going back to login page on refresh

### ISSUE THREAD

**Issue by Gowtham-2016** [bernabe9/redux-react-session#20]
Where are we assigning the authenticated props as true
i don't see anywhere in the code where we are setting its value as true,
i know that the default value is false

**Comment by bernabe9** [comment]
After you logged in (using `saveSession`) the flag` authenticated` will change from false to true, and will be saved in the Redux store within `session.authenticated`.

Your Redux Store should look like this after log in:

```javascript
store =  {
  session: {
    authenticated: true,
    checked: true,
    user: { other user props... }
  },
  other props in the store...
}
```

**Comment by freddyamsterdam** [comment]
@bernabe9 

I'm not entirely sure if this is what @Gowtham-2016 means, but when **refreshing the browser**, the session is a bit late to the party:

<img width="920" alt="screen shot 2018-03-07 at 17 32 16" src="https://user-images.githubusercontent.com/7791750/37104736-be6f06ce-222d-11e8-9412-492b7d5c2736.png">

In my case, my router is rendered conditionally, depending on what the session state is. It seems like the router is actually beating the session to the finish line and performing any route matching before the sessionService is initialised.

Any ideas?

**Comment by freddyamsterdam** [comment]
@Gowtham-2016 #27 might provide the solution to your problem - although I can't quite tell as your issue is a bit too vague to know for sure.
