### ISSUE TITLE
How to get user information of current session

### ISSUE THREAD

**Issue by 5731079821-PP** [bernabe9/redux-react-session#21]
`import {sessionService} from 'redux-react-session';
class AboutUs extends Component {
  render() {
    sessionService.loadSession()
    .then(currentSession => console.log(currentSession))
    .catch(err => console.log(err))
`
this printed out  'undefine', please give me some advice

**Comment by bernabe9** [comment]
Hi, can you give a little bit more of context?

1) Did you follow the initialize steps https://github.com/bernabe9/redux-react-session#usage ?
2) Did you save the session using `sessionService.saveSession` before trying to load it?

**Comment by 5731079821-PP** [comment]
I use your example code and it shows correct result in Home.js . I just want to get user information in another page. Can i use loadUser() or use mapSate() as Home.js

**Comment by bernabe9** [comment]
Both ways should work..

I recommend to use the `mapState` approach but if you want to access directly to the data in the storage using `loadUser` or `loadSesion` is fine.

I tried this in the `Home.js` and it works great:

```javascript
class Home extends Component {
  componentWillMount() {
    sessionService.loadSession().then(session => console.log(session));
    sessionService.loadUser().then(user => console.log(user));
  }
}
```

**Comment by 5731079821-PP** [comment]
Thank you, it works now

**Comment by palidaa** [comment]
@bernabe9 What about how to access logout function out of Home.js
